version: '3.8'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /project/manage.py runserver --insecure 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  postgres_data:
  redisdata: